spring:
  config:
    import: optional:configserver:http://finlearn-config-server:8888
  datasource:
    url: jdbc:postgresql://finlearn-postgres:5432/seasondb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: finlearn-redis
      port: 6379

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://finlearn-eureka:8761/eureka/

internal:
  achievement-service:
    url: http://finlearn-achievement-service:8085
  ranking-service:
    url: http://finlearn-ranking-service:8086

loki:
  url: http://host.docker.internal:3100/loki/api/v1/push
