server:
  port: 8084

spring:
  application:
    name: season-service
  profiles:
    active: local
    group:
      docker: "kafka,topics"
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:seasondb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

internal:
  achievement-service:
    url: ${ACHIEVEMENT_SERVICE_URL:http://localhost:8085}
  ranking-service:
    url: ${RANKING_SERVICE_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
