server:
  port: 8084

spring:
  application:
    name: season-service
  profiles:
    active: local
    group:
      docker: "kafka,topics"
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/seasondb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

internal:
  achievement-service:
    url: http://localhost:8085
  ranking-service:
    url: http://localhost:8086
